from django.urls import path

from .views import (
    HealthCheckAPIView,
    AlipayNotifyAPIView,
    AlipayPrecreateAPIView,
    CommentDeleteAPIView,
    CourseOrderCreateAPIView,
    CourseCommentListCreateAPIView,
    CourseFavoriteToggleAPIView,
    LessonPlayAPIView,
    MyFavoriteListAPIView,
    MyOrderListAPIView,
    OrderStatusAPIView,
    PublicCourseDetailAPIView,
    PublicCourseListAPIView,
    PublicTeacherDetailAPIView,
    R2PresignedUploadAPIView,
    TeacherApplicationAPIView,
    TeacherCourseDetailAPIView,
    TeacherCourseListCreateAPIView,
    TeacherIncomeSummaryAPIView,
    TeacherOrderListAPIView,
    TeacherStatusAPIView,
    TeacherWithdrawListCreateAPIView,
)


urlpatterns = [
    path('health/', HealthCheckAPIView.as_view(), name='health-check'),
    path('courses/', PublicCourseListAPIView.as_view(), name='public-course-list'),
    path('courses/<int:pk>/', PublicCourseDetailAPIView.as_view(), name='public-course-detail'),
    path('courses/<int:pk>/comments/', CourseCommentListCreateAPIView.as_view(), name='course-comment-list-create'),
    path('courses/<int:pk>/favorite/', CourseFavoriteToggleAPIView.as_view(), name='course-favorite-toggle'),
    path('comments/<int:pk>/', CommentDeleteAPIView.as_view(), name='comment-delete'),
    path('favorites/', MyFavoriteListAPIView.as_view(), name='my-favorite-list'),
    path('courses/<int:pk>/orders/', CourseOrderCreateAPIView.as_view(), name='course-order-create'),
    path('orders/', MyOrderListAPIView.as_view(), name='my-order-list'),
    path('orders/<str:order_no>/alipay/precreate/', AlipayPrecreateAPIView.as_view(), name='alipay-precreate'),
    path('orders/<str:order_no>/status/', OrderStatusAPIView.as_view(), name='order-status'),
    path('alipay/notify/', AlipayNotifyAPIView.as_view(), name='alipay-notify'),
    path('teachers/<int:pk>/', PublicTeacherDetailAPIView.as_view(), name='public-teacher-detail'),
    path('lessons/<int:pk>/play/', LessonPlayAPIView.as_view(), name='lesson-play'),
    path('uploads/r2/presign/', R2PresignedUploadAPIView.as_view(), name='r2-presigned-upload'),
    path('teacher/applications/', TeacherApplicationAPIView.as_view(), name='teacher-application'),
    path('teacher/courses/', TeacherCourseListCreateAPIView.as_view(), name='teacher-course-list-create'),
    path('teacher/courses/<int:pk>/', TeacherCourseDetailAPIView.as_view(), name='teacher-course-detail'),
    path('teacher/orders/', TeacherOrderListAPIView.as_view(), name='teacher-order-list'),
    path('teacher/income/summary/', TeacherIncomeSummaryAPIView.as_view(), name='teacher-income-summary'),
    path('teacher/withdraws/', TeacherWithdrawListCreateAPIView.as_view(), name='teacher-withdraw-list-create'),
    path('teacher/status/', TeacherStatusAPIView.as_view(), name='teacher-status'),
]
