# Generated by Django 4.2.30 on 2026-07-26 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('cover', models.FileField(blank=True, upload_to='course/covers/', verbose_name='课程封面')),
                ('title', models.CharField(max_length=120, verbose_name='课程标题')),
                ('summary', models.TextField(blank=True, verbose_name='课程简介')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='课程价格')),
                ('category', models.CharField(max_length=60, verbose_name='课程分类')),
                ('audit_status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='审核状态')),
                ('publish_status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('offline', '已下架')], default='draft', max_length=20, verbose_name='发布状态')),
                ('has_trial', models.BooleanField(default=False, verbose_name='支持试看')),
                ('sort_weight', models.IntegerField(default=0, verbose_name='排序权重')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='点播量')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'ordering': ['-sort_weight', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseChapter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=120, verbose_name='章节标题')),
                ('summary', models.TextField(blank=True, verbose_name='章节简介')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='core.course', verbose_name='课程')),
            ],
            options={
                'verbose_name': '课程章节',
                'verbose_name_plural': '课程章节',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TeacherApplication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('real_name', models.CharField(max_length=50, verbose_name='真实姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('email', models.EmailField(max_length=254, verbose_name='联系邮箱')),
                ('bio', models.TextField(blank=True, verbose_name='申请说明')),
                ('certificate_file', models.FileField(blank=True, upload_to='teacher/certificates/', verbose_name='资质文件')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='审核状态')),
                ('review_note', models.TextField(blank=True, verbose_name='审核备注')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_applications', to=settings.AUTH_USER_MODEL, verbose_name='申请用户')),
            ],
            options={
                'verbose_name': '教师认证申请',
                'verbose_name_plural': '教师认证申请',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('display_name', models.CharField(max_length=80, verbose_name='展示名称')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='教师头衔')),
                ('bio', models.TextField(blank=True, verbose_name='教师简介')),
                ('avatar', models.FileField(blank=True, upload_to='teacher/avatars/', verbose_name='头像')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_profile', to='core.teacherapplication', verbose_name='认证申请')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='教师用户')),
            ],
            options={
                'verbose_name': '教师资料',
                'verbose_name_plural': '教师资料',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='提现金额')),
                ('account_name', models.CharField(max_length=80, verbose_name='收款人')),
                ('account_no', models.CharField(max_length=120, verbose_name='收款账号')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝'), ('paid', '已打款')], default='pending', max_length=20, verbose_name='提现状态')),
                ('review_note', models.TextField(blank=True, verbose_name='审核备注')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='打款时间')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdraws', to='core.teacherprofile', verbose_name='教师')),
            ],
            options={
                'verbose_name': '提现',
                'verbose_name_plural': '提现',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order_no', models.CharField(max_length=64, unique=True, verbose_name='订单号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单金额')),
                ('pay_status', models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('closed', '已关闭'), ('refunded', '已退款')], default='pending', max_length=20, verbose_name='支付状态')),
                ('payment_method', models.CharField(blank=True, choices=[('alipay', '支付宝'), ('wechat', '微信')], max_length=20, verbose_name='支付方式')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.course', verbose_name='课程')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='购买用户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总收入')),
                ('platform_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='平台分成')),
                ('teacher_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='教师分成')),
                ('status', models.CharField(choices=[('pending', '待结算'), ('settled', '已结算')], default='pending', max_length=20, verbose_name='结算状态')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incomes', to='core.course', verbose_name='课程')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='income', to='core.order', verbose_name='订单')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incomes', to='core.teacherprofile', verbose_name='教师')),
            ],
            options={
                'verbose_name': '收益',
                'verbose_name_plural': '收益',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='core.course', verbose_name='课程')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseLesson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=120, verbose_name='小节标题')),
                ('video_file', models.FileField(blank=True, upload_to='course/videos/', verbose_name='视频文件')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='视频时长秒数')),
                ('is_trial', models.BooleanField(default=False, verbose_name='是否试看')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.coursechapter', verbose_name='章节')),
            ],
            options={
                'verbose_name': '课程小节',
                'verbose_name_plural': '课程小节',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='core.teacherprofile', verbose_name='教师'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='评分')),
                ('is_visible', models.BooleanField(default=True, verbose_name='是否显示')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.course', verbose_name='课程')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.courselesson', verbose_name='小节')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='unique_user_course_favorite'),
        ),
    ]
