# Generated by Django 4.2.30 on 2026-07-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='audit_reject_reason',
            field=models.TextField(blank=True, verbose_name='审核拒绝原因'),
        ),
        migrations.AddField(
            model_name='course',
            name='suitable_audience',
            field=models.TextField(blank=True, verbose_name='适合人群'),
        ),
    ]
