# Generated by Django 4.2.30 on 2026-07-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course_audit_reject_reason_course_suitable_audience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cover',
            field=models.CharField(blank=True, max_length=500, verbose_name='课程封面'),
        ),
        migrations.AlterField(
            model_name='courselesson',
            name='video_file',
            field=models.CharField(blank=True, max_length=500, verbose_name='视频文件'),
        ),
    ]
