# Generated by Django 4.2.30 on 2026-07-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_course_cover_alter_courselesson_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselesson',
            name='duration',
            field=models.PositiveIntegerField(default=0, verbose_name='视频时长秒数'),
        ),
        migrations.AddField(
            model_name='courselesson',
            name='hls_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='HLS地址'),
        ),
        migrations.AddField(
            model_name='courselesson',
            name='resolution',
            field=models.CharField(blank=True, max_length=50, verbose_name='视频分辨率'),
        ),
        migrations.AddField(
            model_name='courselesson',
            name='transcode_status',
            field=models.CharField(choices=[('pending', '待转码'), ('processing', '转码中'), ('ready', '已完成'), ('failed', '转码失败')], default='pending', max_length=20, verbose_name='转码状态'),
        ),
    ]
